### ISSUE TITLE
How can I use this library for this demand?

### ISSUE THREAD

**Issue by Comdex** [winlabs/gowin32#32]
how to realize such a function : when the windows system insert a flash disk , my golang program can recieve a reminder , and found the flash disk's path , Thanks!

**Comment by dgolub** [comment]
Right now, this is not a capability that we support in gowin32, so for now you'll need to call into Win32 directly.  The Win32 API function that you'd need to use is called `RegisterDeviceNotification`.  If you're interested in adding this capability to gowin32, feel free to submit a pull request.
