### ISSUE TITLE
pkg.go.dev license issue

### ISSUE THREAD

**Issue by ozanh** [winlabs/gowin32#82]
Hello,

New pkg.go.dev which is default Go documentation viewer does not show gowin32 documentation because it cannot determine library's license although gowin32 has a redistributable Apache license.
https://pkg.go.dev/github.com/winlabs/gowin32

**Comment by dgolub** [comment]
Thanks for the bug report!  I've opened a PR and will merge the fix as soon as it's approved by one of my colleagues.
